import datetime  # help(datetime.time)
gvr = datetime.date(1956, 1, 31)
print(gvr)
print(gvr.year)
print(gvr.month)
print(gvr.day)
print()

mill = datetime.date(2000, 1, 1)
dt = datetime.timedelta(100)
print(f'{mill} + {dt.days} =', mill + dt)
print()

l_date = datetime.date(2017, 3, 30)
l_time = datetime.time(22, 27, 0)
l_datetime = datetime.datetime(2017, 3, 30, 22, 27, 0)
print(l_date)
print(l_time)
print(l_datetime)
print()
print(l_date.year, l_date.month, l_date.day)
print(l_time.hour, l_time.minute, l_time.second)
print()

now = datetime.datetime.today()
print(now)
print(now.microsecond)
